In [1]:
from pandas import Series, DataFrame
import pandas as pd
%pylab inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

Populating the interactive namespace from numpy and matplotlib

In [2]:
data = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
data_y = data['Attrition'] # make y values
data_x = data.drop(['Attrition'],axis = 1) # the rest of the df

# dropping columns that an employer cannot affect
data_x = data_x.drop(['Age','DistanceFromHome','Education','EducationField','Gender','MaritalStatus','NumCompaniesWorked','Over18','PerformanceRating','RelationshipSatisfaction','TotalWorkingYears','YearsAtCompany'],axis = 1)
data_x = pd.get_dummies(data_x)
xtrain, xtest, ytrain, ytest = train_test_split(data_x,data_y, test_size = .125, random_state = None)

In [4]:
model = LogisticRegression().fit(xtrain,ytrain)
pred = model.predict(xtest)
print metrics.balanced_accuracy_score(ytest,pred)

0.6086956521739131

In [5]:
weights = Series(model.coef_[0], index = data_x.columns.values)
weights.sort_values()

OverTime_No                         -0.817529
StockOptionLevel                    -0.498187
JobInvolvement                      -0.464635
EnvironmentSatisfaction             -0.354248
JobSatisfaction                     -0.341245
Department_Research & Development   -0.332297
JobRole_Research Scientist          -0.313404
WorkLifeBalance                     -0.304295
BusinessTravel_Non-Travel           -0.260454
TrainingTimesLastYear               -0.183635
JobRole_Healthcare Representative   -0.170547
JobLevel                            -0.125646
BusinessTravel_Travel_Rarely        -0.113583
YearsWithCurrManager                -0.101695
JobRole_Manufacturing Director      -0.099480
YearsInCurrentRole                  -0.093255
JobRole_Research Director           -0.044627
PercentSalaryHike                   -0.041826
HourlyRate                          -0.002455
DailyRate                           -0.000288
MonthlyIncome                       -0.000113
EmployeeNumber                      -0.000096
MonthlyRate                          0.000016
EmployeeCount                        0.000873
JobRole_Manager                      0.010506
JobRole_Sales Executive              0.024188
Department_Human Resources           0.042519
JobRole_Human Resources              0.055750
StandardHours                        0.069814
YearsSinceLastPromotion              0.142354
JobRole_Sales Representative         0.263826
JobRole_Laboratory Technician        0.274661
Department_Sales                     0.290650
BusinessTravel_Travel_Frequently     0.374909
OverTime_Yes                         0.818402
dtype: float64